import { gql } from "@apollo/client";

export const ORDERS = gql`
  query($id:ID){
    orders(id:$id){
      edges{
        node{
          id
          createdOn
          isDeleted
          deletedOn
          finalPrice
          status
          deliveryDate
          finalPrice
          dueAmount
          paidAmount
          note
          orderCarts(addedFor: "141"){
            edges{
              node{
                id
                quantity
                priceWithTax
                totalPriceWithTax
                orderedQuantity
                item{
                  id
                  priceWithTax
                  name
                  attachments{
                  edges{
                    node{
                      fileUrl
                      isCover
                    }
                  }
                }
                }
              }
            }
          }
        }
      }
    }
}
`
export const ORDER = gql`
  query ($id:ID!,$addedFor: String) {
    order(id:$id){
      id
      createdOn
      isDeleted
      deliveryDate
      finalPrice
      status
      createdOn
      isDeleted
      paymentType
      companyAllowance
      shippingCharge
      dueAmount
      discountAmount
      paidAmount
      isFullPaid
      employeeDueAmount
      companyDueAmount
      note
      statuses{
        edges{
          node{
            id
          status
          note
              createdOn
            }
          }
        }
        shippingAddress{
        address
        city
        state
        postCode
        fullName
        phone
          }
      company{
        id
        name
        email
      }
    billingAddress{
      firstName
      lastName
      address
      phone
    }
    orderCarts(addedFor:$addedFor){
      edges{
        node{
          id
          cancelled
          orderedQuantity
          priceWithTax
          totalPriceWithTax
          item{
            id
            priceWithTax
            name
            attachments{
              edges{
                node{
                  id
                  fileUrl
                  isCover
                }
              }
            }
            category{
              id
              name
            }
          }
          users{
            edges{
              node{
                id
                dueAmount
                alterCart{ # if alterCart has data that means there is update request in user-cart
                  id # need to use this id for confirmUserCartUpdate
                  status
                   previousCart{
                    dueAmount
                    id
                    priceWithTax
                    item{
                      id
                      priceWithTax
                      name
                      category{
                        id
                        name
                      }
                    }
                  }
                  base{
                    id
                    addedFor{
                      id
                      username
                       firstName
                      lastName
                      email
                      phone
                      isStaff
                      photoUrl
                      role
                    }
                  }
                  item{
                    id
                    name
                    priceWithTax
                    attachments{
                        edges{
                          node{
                            fileUrl
                            isCover
                          }
                        }
                      }
                    category{
                      name
                      id
                    }
                  }
                }
                addedFor{
                  id
                  username
                  email
                  firstName
                  lastName
                  postCode
                  photoUrl
                  role
                  isDeleted
                  phone
                  dueAmount
                }
              }
            }
          }
        }
      }
    }
  }
  }
`